services:
  - type: web
    name: combridge-polytechnic
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Combridge School Management System
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:hE3BMwpHZmltFP2rkssDa8BVf8foyrd+5U7nJWwdQho=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql111.infinityfree.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: if0_42854964_polytechnic
      - key: DB_USERNAME
        value: if0_42854964
      - key: DB_PASSWORD
        value: GVhCdPtrQj0Erv
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SCHOOL_NAME
        value: Combridge Centre for Polytechnic Studies
      - key: SCHOOL_EMAIL
        value: combridgecentre@gmail.com
      - key: SCHOOL_PHONE
        value: +256 393 258 879
      - key: SCHOOL_WHATSAPP
        value: +256 787 803 099
